- name: Download GitLab Runner binary
  get_url:
    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
    dest: /usr/local/bin/gitlab-runner
    mode: '0755'

- name: Create GitLab Runner user
  user:
    name: gitlab-runner
    comment: 'GitLab Runner'
    create_home: yes
    shell: /bin/bash

- name: Install GitLab Runner as a service
  command: gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
  args:
    creates: /etc/systemd/system/gitlab-runner.service
  async: 600
  poll: 0
  become: yes

- name: Start GitLab Runner service
  command: gitlab-runner start
  async: 600
  poll: 0
  become: yes

- name: Register GitLab Runner
  shell: |
    gitlab-runner register --non-interactive --name {{ gitlab_runner_name }} --url {{ gitlab_url }} --registration-token {{ gitlab_registration_token }} --executor shell
  environment:
    PATH: "{{ lookup('env','PATH') }}"

- name: Add user '{{ gitlab_runner_user }}' to the docker group
  user:
    name: "{{ gitlab_runner_user }}"
    groups: docker
    append: yes

- name: Add user '{{ gitlab_runner_user }}' to sudo group
  user:
    name: "{{ gitlab_runner_user }}"
    groups: sudo
    append: yes

- name: Remove '.bash_logout' file from GitLab Runner user
  file:
    path: /home/{{ gitlab_runner_user }}/.bash_logout
    state: absent

- name: Restart GitLab Runner service
  systemd:
    name: gitlab-runner
    state: restarted
